name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and publish to github packages
      run: |
        VERSION=$(date +%s)
        docker build . --file Dockerfile --tag docker.pkg.github.com/prashanth-sams/json-server/app:${VERSION}
        docker login docker.pkg.github.com --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push docker.pkg.github.com/prashanth-sams/json-server/app:${VERSION}